// =============================================================================
// Task #293 — One-off backfill: flag duplicate live fee consents as
// `superseded` so the new partial unique index on `feeConsents`
// (clientId, adviceRecordId, feeType, accountNumber) WHERE
// renewal_status IN ('active', 'renewal_due') can be applied without
// failing on pre-existing rows.
// -----------------------------------------------------------------------------
// Strategy:
//   1. Find every (clientId, adviceRecordId, feeType, accountNumber) group
//      that has more than one row in renewal_status active|renewal_due.
//   2. Keep the row with the most recent consentedAt as the surviving
//      "live" consent. Mark every other row in the group as
//      renewal_status='superseded' with `supersededAt = now()` and
//      `supersededReason = 'pre-launch backfill: duplicate active consent'`.
//      `supersededByRequestId` is intentionally NULL — these duplicates
//      were not generated by the new admin Supersede flow, so there is
//      no fresh request to point at.
//   3. Write an `audit_logs` row per flagged consent so the regulator-
//      grade trail explains who did what and why.
//
// Idempotency:
//   The script only modifies rows that are still in active|renewal_due
//   AND have at least one newer sibling. Re-running after a successful
//   pass therefore touches zero rows.
//
// Safety:
//   No money moves here — this only edits the `renewal_status` and the
//   three new `superseded*` columns introduced by the same task. The
//   kill-switch on deductions is unaffected.
//
// Usage:
//   tsx scripts/backfill-fee-consent-supersedes.ts            # dry-run
//   tsx scripts/backfill-fee-consent-supersedes.ts --apply    # commit
// =============================================================================

import { and, desc, eq, sql } from "drizzle-orm";
import { db } from "../server/db";
import { feeConsents, auditLogs } from "../shared/schema";

const APPLY = process.argv.includes("--apply");

interface DupGroup {
  clientId: number;
  adviceRecordId: number;
  feeType: string;
  accountNumber: string;
  count: number;
}

async function findDuplicateGroups(): Promise<DupGroup[]> {
  // GROUP BY the four columns the new partial unique index covers, and
  // only flag groups that currently have more than one live row.
  const result = await db.execute<DupGroup>(sql`
    SELECT
      client_id          AS "clientId",
      advice_record_id   AS "adviceRecordId",
      fee_type           AS "feeType",
      account_number     AS "accountNumber",
      COUNT(*)::int      AS "count"
    FROM fee_consents
    WHERE renewal_status IN ('active', 'renewal_due')
    GROUP BY client_id, advice_record_id, fee_type, account_number
    HAVING COUNT(*) > 1
  `);
  return result.rows;
}

async function main() {
  console.log(
    `[backfill-fee-consent-supersedes] mode=${APPLY ? "APPLY" : "DRY-RUN"}`,
  );
  const groups = await findDuplicateGroups();
  if (groups.length === 0) {
    console.log("No duplicate active consent groups found. Nothing to do.");
    return;
  }
  console.log(`Found ${groups.length} duplicate active-consent group(s).`);

  let toFlag: number[] = [];
  for (const g of groups) {
    const rowsInGroup = await db
      .select({
        id: feeConsents.id,
        consentedAt: feeConsents.consentedAt,
      })
      .from(feeConsents)
      .where(
        and(
          eq(feeConsents.clientId, g.clientId),
          eq(feeConsents.adviceRecordId, g.adviceRecordId),
          eq(feeConsents.feeType, g.feeType),
          eq(feeConsents.accountNumber, g.accountNumber),
          sql`${feeConsents.renewalStatus} IN ('active', 'renewal_due')`,
        ),
      )
      .orderBy(desc(feeConsents.consentedAt));
    // Keep the most recent (index 0); flag the rest.
    const losers = rowsInGroup.slice(1).map((r) => r.id);
    console.log(
      `  group client=${g.clientId} advice=${g.adviceRecordId} feeType=${g.feeType} ` +
        `account=${g.accountNumber}: keep #${rowsInGroup[0].id}, ` +
        `flag #${losers.join(", #")}`,
    );
    toFlag.push(...losers);
  }

  if (!APPLY) {
    console.log(
      `\nDRY-RUN — would mark ${toFlag.length} consent row(s) as 'superseded'. ` +
        `Re-run with --apply to commit.`,
    );
    return;
  }

  await db.transaction(async (tx) => {
    for (const id of toFlag) {
      const [before] = await tx
        .select()
        .from(feeConsents)
        .where(eq(feeConsents.id, id))
        .for("update")
        .limit(1);
      if (!before) continue;
      // Belt-and-braces: re-check renewal_status under the row lock so a
      // concurrent admin Supersede that already moved the row doesn't get
      // double-stamped.
      if (
        before.renewalStatus !== "active" &&
        before.renewalStatus !== "renewal_due"
      ) {
        console.log(`  skip #${id}: renewal_status now '${before.renewalStatus}'`);
        continue;
      }
      const [after] = await tx
        .update(feeConsents)
        .set({
          renewalStatus: "superseded",
          supersededAt: new Date(),
          supersededReason: "pre-launch backfill: duplicate active consent",
          updatedAt: new Date(),
        })
        .where(eq(feeConsents.id, id))
        .returning();
      await tx.insert(auditLogs).values({
        userId: null,
        action: "fee_consent_superseded_backfill",
        entityType: "fee_consent",
        entityId: String(id),
        metadata: {
          before: {
            renewalStatus: before.renewalStatus,
            supersededAt: before.supersededAt,
            supersededReason: before.supersededReason,
          },
          after: {
            renewalStatus: after.renewalStatus,
            supersededAt: after.supersededAt,
            supersededReason: after.supersededReason,
          },
          source: "scripts/backfill-fee-consent-supersedes.ts",
          reason: "pre-launch backfill: duplicate active consent",
        },
        ipAddress: null,
      });
    }
  });
  console.log(`\nApplied — flagged ${toFlag.length} row(s) as 'superseded'.`);
}

main().then(
  () => process.exit(0),
  (err) => {
    console.error("[backfill-fee-consent-supersedes] FAILED:", err);
    process.exit(1);
  },
);
